package kg.timmitof.keyboard.presentation.theme

import androidx.compose.ui.graphics.Color

data class KeyboardLightColor(
    override val keyboardBackground: Color = Color(0xFFE8E8E8),
    override val keyButtonBackground: Color = Color(0xFFFFFFFF),
    override val keyTextColor: Color = Color(0xFF1B1D21),
    override val keyButtonPressedBackground: Color = Color(0xFFD0D0D0),
    override val keyButtonShadow: Color = Color(0x2E000000),
    override val keySpecialButtonBackground: Color = Color(0xFFBFC4CB),
    override val keySpecialTextColor: Color = Color(0xFF1B1D21),
    override val keyLabelColor: Color = keyTextColor,
    override val keySpecialLabelColor: Color = keySpecialTextColor,
    override val keyAccentBackground: Color = Color(0xFF6D4BD8),
    override val keyAccentTextColor: Color = Color(0xFFFFFFFF),
    override val keyEnterBackground: Color = keySpecialButtonBackground,
    override val keyEnterTextColor: Color = keySpecialTextColor,
    override val keyEnterPressedBackground: Color = keyButtonPressedBackground,
    override val keyOutline: Color = Color(0x33000000),
    override val noticeBackground: Color = Color(0xFFDCD3EF),
    override val noticeTextColor: Color = Color(0xFF3F2A8C),
    override val overlayBackground: Color = keyboardBackground,
    override val overlayTitleColor: Color = keyTextColor,
    override val overlaySubtitleColor: Color = Color(0xFF5C6066),
    override val overlayIconColor: Color = Color(0xFF4A4D53),
    override val overlayAccent: Color = keyAccentBackground,
    override val overlayAccentTextColor: Color = keyAccentTextColor,
    override val overlayDivider: Color = Color(0x1F000000),
    override val overlayChipBackground: Color = Color(0xFFDCDEE1),
    override val overlayChipTextColor: Color = keyTextColor,
    override val overlayActionBackground: Color = keyButtonBackground,
    override val overlayActionTextColor: Color = keyTextColor,
    override val overlayControlTrack: Color = keyButtonPressedBackground,
    override val overlayControlLabelColor: Color = Color(0xFF45484D),
) : KeyboardColorScheme

data class KeyboardDarkColor(
    override val keyboardBackground: Color = Color(0xFF1A1A1A),
    override val keyButtonBackground: Color = Color(0xFF303030),
    override val keyTextColor: Color = Color(0xFFFFFFFF),
    override val keyButtonPressedBackground: Color = Color(0xFF3D3D3D),
    override val keyButtonShadow: Color = Color(0x99000000),
    override val keySpecialButtonBackground: Color = Color(0xFF1F1F1F),
    override val keySpecialTextColor: Color = Color(0xFFB9B9B9),
    override val keyLabelColor: Color = keyTextColor,
    override val keySpecialLabelColor: Color = keySpecialTextColor,
    override val keyAccentBackground: Color = Color(0xFFE3B7F3),
    override val keyAccentTextColor: Color = Color(0xFF3A1B52),
    override val keyEnterBackground: Color = keySpecialButtonBackground,
    override val keyEnterTextColor: Color = keySpecialTextColor,
    override val keyEnterPressedBackground: Color = keyButtonPressedBackground,
    override val keyOutline: Color = Color(0x40FFFFFF),
    override val noticeBackground: Color = Color(0xFF2E2440),
    override val noticeTextColor: Color = Color(0xFFD9C6F5),
    override val overlayBackground: Color = keyboardBackground,
    override val overlayTitleColor: Color = keyTextColor,
    override val overlaySubtitleColor: Color = Color(0xFF9A9A9A),
    override val overlayIconColor: Color = keySpecialTextColor,
    override val overlayAccent: Color = keyAccentBackground,
    override val overlayAccentTextColor: Color = keyAccentTextColor,
    override val overlayDivider: Color = Color(0x1FFFFFFF),
    override val overlayChipBackground: Color = Color(0xFF2A2A2A),
    override val overlayChipTextColor: Color = Color(0xFFE9E9E9),
    override val overlayActionBackground: Color = keyButtonBackground,
    override val overlayActionTextColor: Color = keyTextColor,
    override val overlayControlTrack: Color = keyButtonPressedBackground,
    override val overlayControlLabelColor: Color = Color(0xFFC4C4C4),
) : KeyboardColorScheme
