package kg.timmitof.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val AppLightColorScheme = lightColorScheme(
    primary = AppColor.primaryLight,
    onPrimary = AppColor.onPrimaryLight,
    primaryContainer = AppColor.primaryContainerLight,
    onPrimaryContainer = AppColor.onPrimaryContainerLight,
    secondary = AppColor.secondaryLight,
    onSecondary = AppColor.onSecondaryLight,
    secondaryContainer = AppColor.secondaryContainerLight,
    onSecondaryContainer = AppColor.onSecondaryContainerLight,
    tertiary = AppColor.tertiaryLight,
    onTertiary = AppColor.onTertiaryLight,
    tertiaryContainer = AppColor.tertiaryContainerLight,
    onTertiaryContainer = AppColor.onTertiaryContainerLight,
    error = AppColor.errorLight,
    onError = AppColor.onErrorLight,
    errorContainer = AppColor.errorContainerLight,
    onErrorContainer = AppColor.onErrorContainerLight,
    background = AppColor.backgroundLight,
    onBackground = AppColor.onBackgroundLight,
    surface = AppColor.surfaceLight,
    onSurface = AppColor.onSurfaceLight,
    surfaceVariant = AppColor.surfaceVariantLight,
    onSurfaceVariant = AppColor.onSurfaceVariantLight,
    outline = AppColor.outlineLight,
    outlineVariant = AppColor.outlineVariantLight,
    scrim = AppColor.scrimLight,
    inverseSurface = AppColor.inverseSurfaceLight,
    inverseOnSurface = AppColor.inverseOnSurfaceLight,
    inversePrimary = AppColor.inversePrimaryLight,
    surfaceDim = AppColor.surfaceDimLight,
    surfaceBright = AppColor.surfaceBrightLight,
    surfaceContainerLowest = AppColor.surfaceContainerLowestLight,
    surfaceContainerLow = AppColor.surfaceContainerLowLight,
    surfaceContainer = AppColor.surfaceContainerLight,
    surfaceContainerHigh = AppColor.surfaceContainerHighLight,
    surfaceContainerHighest = AppColor.surfaceContainerHighestLight,
)

val AppDarkColorScheme = darkColorScheme(
    primary = AppColor.primaryDark,
    onPrimary = AppColor.onPrimaryDark,
    primaryContainer = AppColor.primaryContainerDark,
    onPrimaryContainer = AppColor.onPrimaryContainerDark,
    secondary = AppColor.secondaryDark,
    onSecondary = AppColor.onSecondaryDark,
    secondaryContainer = AppColor.secondaryContainerDark,
    onSecondaryContainer = AppColor.onSecondaryContainerDark,
    tertiary = AppColor.tertiaryDark,
    onTertiary = AppColor.onTertiaryDark,
    tertiaryContainer = AppColor.tertiaryContainerDark,
    onTertiaryContainer = AppColor.onTertiaryContainerDark,
    error = AppColor.errorDark,
    onError = AppColor.onErrorDark,
    errorContainer = AppColor.errorContainerDark,
    onErrorContainer = AppColor.onErrorContainerDark,
    background = AppColor.backgroundDark,
    onBackground = AppColor.onBackgroundDark,
    surface = AppColor.surfaceDark,
    onSurface = AppColor.onSurfaceDark,
    surfaceVariant = AppColor.surfaceVariantDark,
    onSurfaceVariant = AppColor.onSurfaceVariantDark,
    outline = AppColor.outlineDark,
    outlineVariant = AppColor.outlineVariantDark,
    scrim = AppColor.scrimDark,
    inverseSurface = AppColor.inverseSurfaceDark,
    inverseOnSurface = AppColor.inverseOnSurfaceDark,
    inversePrimary = AppColor.inversePrimaryDark,
    surfaceDim = AppColor.surfaceDimDark,
    surfaceBright = AppColor.surfaceBrightDark,
    surfaceContainerLowest = AppColor.surfaceContainerLowestDark,
    surfaceContainerLow = AppColor.surfaceContainerLowDark,
    surfaceContainer = AppColor.surfaceContainerDark,
    surfaceContainerHigh = AppColor.surfaceContainerHighDark,
    surfaceContainerHighest = AppColor.surfaceContainerHighestDark,
)